# add the linters you want stickler to use for this project
linters:
  rubocop:
    display_cop_names: true
      config: './rubocop.yml'
        eslint:
          config: './.eslintrc.json'

files:
  ignore:
    - 'bin/*'
    - 'db/*'
    - 'config/*'
    - 'Guardfile'
    - 'Rakefile'
    - 'README.md'
    - 'node_modules/**/*'
